featured_category:
  type: integer
  default: 0
featured_tags:
  type: list
  list_type: tag
  default: "featured"
topic_source:
  type: enum
  default: "top"
  choices:
    - latest
    - top
top_period:
  type: enum
  default: "yearly"
  choices:
    - "yearly"
    - "quarterly"
    - "monthly"
    - "weekly"
    - "daily"
randomize_topics: true
display_when_unfiltered: true
display_on_categories: true
display_categories:
  type: list
  list_type: category
  default: ""
maximum_topic_count: 5
scope_to_category: false
display_mobile: false
